apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: actions-cluster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: fercdevv/frontend-k8:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: actions-cluster
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80